<a href="https://colab.research.google.com/github/davivi-py/analise-acidentes-aereos-cenipa/blob/main/an%C3%A1lise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np

ocorrencia = pd.read_csv('analise-acidentes-aereos-cenipa/data/ocorrencia.csv', encoding='latin-1', sep=';')
aeronave = pd.read_csv('analise-acidentes-aereos-cenipa/data/aeronave.csv', encoding='latin-1', sep=';')
ocorrencia_tipo = pd.read_csv('analise-acidentes-aereos-cenipa/data/ocorrencia_tipo.csv', encoding='latin-1', sep=';')



ocorrencia.shape
ocorrencia.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,83097,83097,83097,83097,83097,ACIDENTE,-2.352.777.777.777,-4.563.944.444.444,PARAIBUNA,SP,...,31/12/2023,18:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,83085,83085,83085,83085,83085,INCIDENTE,-9.868.333.333.333,-6.789.805.555.555,RIO BRANCO,AC,...,13/12/2023,11:33:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2,83074,83074,83074,83074,83074,INCIDENTE,-1.962.444.444.444,-4.397.194.444.444,BELO HORIZONTE,MG,...,20/12/2023,20:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3,83063,83063,83063,83063,83063,INCIDENTE,-1.587.111.111.111,-4.791.861.111.111,BRASÍLIA,DF,...,29/12/2023,21:20:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,83051,83051,83051,83051,83051,INCIDENTE,-4.871.388.888.888,-668.975,CARAUARI,AM,...,09/12/2023,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [18]:
aeronave.shape
aeronave.head()

,codigo_ocorrencia2,aeronave_matricula,aeronave_operador_categoria,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,...,aeronave_pais_fabricante,aeronave_pais_registro,aeronave_registro_categoria,aeronave_registro_segmento,aeronave_voo_origem,aeronave_voo_destino,aeronave_fase_operacao,aeronave_tipo_operacao,aeronave_nivel_dano,aeronave_fatalidades_total
0,83097,PRHDB,***,HELICÓPTERO,ROBINSON HELICOPTER,R44,R44,PISTÃO,MONOMOTOR,1088,...,BRASIL,BRASIL,HELICÓPTERO,PARTICULAR,CAMPO DE MARTE - SP,MAROUM,CRUZEIRO,***,SUBSTANCIAL,4
1,83085,PTEEK,***,AVIÃO,EMBRAER,EMB-810C,PA34,PISTÃO,BIMOTOR,2073,...,BRASIL,BRASIL,AVIÃO,TÁXI AÉREO,FAZENDA ÁGUA LIMPA,PLÁCIDO DE CASTRO,TÁXI,NÃO REGULAR,LEVE,0
2,83074,PSAEN,***,AVIÃO,EMBRAER,ERJ 190-400,E295,JATO,BIMOTOR,61200,...,BRASIL,BRASIL,AVIÃO,REGULAR,VIRACOPOS,TANCREDO NEVES,INDETERMINADA,REGULAR,NENHUM,0
3,83063,PRGZW,***,AVIÃO,BOEING COMPANY,737-86N,B738,NaN,BIMOTOR,79015,...,BRASIL,BRASIL,AVIÃO,REGULAR,GOVERNADOR ANDRÉ FRANCO MONTORO,PRESIDENTE JUSCELINO KUBITSCHEK,POUSO,REGULAR,NENHUM,0
4,83051,PRPDP,***,***,ATR - GIE AVIONS DE TRANSPORT RÉGIONAL,ATR-42-500,AT45,TURBOÉLICE,BIMOTOR,18600,...,BRASIL,BRASIL,***,REGULAR,PORTO URUCU,CARAUARI,TÁXI,REGULAR,NENHUM,0

In [20]:
ocorrencia_tipo.shape
ocorrencia_tipo.head()

,codigo_ocorrencia1,ocorrencia_tipo,ocorrencia_tipo_categoria,taxonomia_tipo_icao
0,83097,INDETERMINADO,INDETERMINADO,UNK
1,83085,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP
2,83074,COLISÃO COM AVE,COLISÃO COM AVE,BIRD
3,83063,COLISÃO COM AVE,COLISÃO COM AVE,BIRD
4,83051,COLISÃO COM AVE,COLISÃO COM AVE,BIRD

In [26]:
ocorrencia.isna().sum()

codigo_ocorrencia2               0
aeronave_matricula               0
aeronave_operador_categoria      0
aeronave_tipo_veiculo            0
aeronave_fabricante              1
aeronave_modelo                  2
aeronave_tipo_icao               1
aeronave_motor_tipo            113
aeronave_motor_quantidade        0
aeronave_pmd                     0
aeronave_pmd_categoria           0
aeronave_assentos              454
aeronave_ano_fabricacao        303
aeronave_pais_fabricante         0
aeronave_pais_registro           0
aeronave_registro_categoria      0
aeronave_registro_segmento       0
aeronave_voo_origem              1
aeronave_voo_destino             1
aeronave_fase_operacao           0
aeronave_tipo_operacao           0
aeronave_nivel_dano              0
aeronave_fatalidades_total       0
dtype: int64

In [27]:
aeronave.isna().sum()

codigo_ocorrencia2               0
aeronave_matricula               0
aeronave_operador_categoria      0
aeronave_tipo_veiculo            0
aeronave_fabricante              1
aeronave_modelo                  2
aeronave_tipo_icao               1
aeronave_motor_tipo            113
aeronave_motor_quantidade        0
aeronave_pmd                     0
aeronave_pmd_categoria           0
aeronave_assentos              454
aeronave_ano_fabricacao        303
aeronave_pais_fabricante         0
aeronave_pais_registro           0
aeronave_registro_categoria      0
aeronave_registro_segmento       0
aeronave_voo_origem              1
aeronave_voo_destino             1
aeronave_fase_operacao           0
aeronave_tipo_operacao           0
aeronave_nivel_dano              0
aeronave_fatalidades_total       0
dtype: int64

In [28]:
ocorrencia_tipo.isna().sum()

codigo_ocorrencia1           0
ocorrencia_tipo              0
ocorrencia_tipo_categoria    0
taxonomia_tipo_icao          0
dtype: int64