<a href="https://colab.research.google.com/github/davivi-py/analise-acidentes-aereos-cenipa/blob/main/an%C3%A1lise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/davivi-py/analise-acidentes-aereos-cenipa

Cloning into 'analise-acidentes-aereos-cenipa'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 26 (delta 1), reused 9 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (26/26), 1.03 MiB | 10.11 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [8]:
import pandas as pd
import numpy as np
import sqlite3

ocorrencia = pd.read_csv('analise-acidentes-aereos-cenipa/data/ocorrencia.csv', encoding='latin-1', sep=';')
aeronave = pd.read_csv('analise-acidentes-aereos-cenipa/data/aeronave.csv', encoding='latin-1', sep=';')
ocorrencia_tipo = pd.read_csv('analise-acidentes-aereos-cenipa/data/ocorrencia_tipo.csv', encoding='latin-1', sep=';') # carregando as 3 tabelas

con = sqlite3.connect('db') # criação de banco de dados local usando sqlite3

ocorrencia.to_sql(name = "ocorrencia",con = con, if_exists =  'replace')   # colocando os 3 dataframes no banco de dados SQL
aeronave.to_sql(name = "aeronave",con = con, if_exists = 'replace')
ocorrencia_tipo.to_sql(name = "ocorrencia_tipo",con = con, if_exists ='replace')

10284

In [ ]:
ocorrencia.shape  # inspecao inicial
ocorrencia.head()

In [ ]:
aeronave.shape
aeronave.head() # inspecao inicial

,codigo_ocorrencia2,aeronave_matricula,aeronave_operador_categoria,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,...,aeronave_pais_fabricante,aeronave_pais_registro,aeronave_registro_categoria,aeronave_registro_segmento,aeronave_voo_origem,aeronave_voo_destino,aeronave_fase_operacao,aeronave_tipo_operacao,aeronave_nivel_dano,aeronave_fatalidades_total
0,83097,PRHDB,***,HELICÓPTERO,ROBINSON HELICOPTER,R44,R44,PISTÃO,MONOMOTOR,1088,...,BRASIL,BRASIL,HELICÓPTERO,PARTICULAR,CAMPO DE MARTE - SP,MAROUM,CRUZEIRO,***,SUBSTANCIAL,4
1,83085,PTEEK,***,AVIÃO,EMBRAER,EMB-810C,PA34,PISTÃO,BIMOTOR,2073,...,BRASIL,BRASIL,AVIÃO,TÁXI AÉREO,FAZENDA ÁGUA LIMPA,PLÁCIDO DE CASTRO,TÁXI,NÃO REGULAR,LEVE,0
2,83074,PSAEN,***,AVIÃO,EMBRAER,ERJ 190-400,E295,JATO,BIMOTOR,61200,...,BRASIL,BRASIL,AVIÃO,REGULAR,VIRACOPOS,TANCREDO NEVES,INDETERMINADA,REGULAR,NENHUM,0
3,83063,PRGZW,***,AVIÃO,BOEING COMPANY,737-86N,B738,NaN,BIMOTOR,79015,...,BRASIL,BRASIL,AVIÃO,REGULAR,GOVERNADOR ANDRÉ FRANCO MONTORO,PRESIDENTE JUSCELINO KUBITSCHEK,POUSO,REGULAR,NENHUM,0
4,83051,PRPDP,***,***,ATR - GIE AVIONS DE TRANSPORT RÉGIONAL,ATR-42-500,AT45,TURBOÉLICE,BIMOTOR,18600,...,BRASIL,BRASIL,***,REGULAR,PORTO URUCU,CARAUARI,TÁXI,REGULAR,NENHUM,0

In [ ]:
ocorrencia_tipo.shape
ocorrencia_tipo.head() # inspecao inicial

,codigo_ocorrencia1,ocorrencia_tipo,ocorrencia_tipo_categoria,taxonomia_tipo_icao
0,83097,INDETERMINADO,INDETERMINADO,UNK
1,83085,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,FALHA OU MAU FUNCIONAMENTO DE SISTEMA / COMPON...,SCF-NP
2,83074,COLISÃO COM AVE,COLISÃO COM AVE,BIRD
3,83063,COLISÃO COM AVE,COLISÃO COM AVE,BIRD
4,83051,COLISÃO COM AVE,COLISÃO COM AVE,BIRD

In [ ]:
ocorrencia.isna().sum() # contagem de NaN (nulos)

codigo_ocorrencia2               0
aeronave_matricula               0
aeronave_operador_categoria      0
aeronave_tipo_veiculo            0
aeronave_fabricante              1
aeronave_modelo                  2
aeronave_tipo_icao               1
aeronave_motor_tipo            113
aeronave_motor_quantidade        0
aeronave_pmd                     0
aeronave_pmd_categoria           0
aeronave_assentos              454
aeronave_ano_fabricacao        303
aeronave_pais_fabricante         0
aeronave_pais_registro           0
aeronave_registro_categoria      0
aeronave_registro_segmento       0
aeronave_voo_origem              1
aeronave_voo_destino             1
aeronave_fase_operacao           0
aeronave_tipo_operacao           0
aeronave_nivel_dano              0
aeronave_fatalidades_total       0
dtype: int64

In [ ]:
aeronave.isna().sum() # contagem de NaN (nulos)

codigo_ocorrencia2               0
aeronave_matricula               0
aeronave_operador_categoria      0
aeronave_tipo_veiculo            0
aeronave_fabricante              1
aeronave_modelo                  2
aeronave_tipo_icao               1
aeronave_motor_tipo            113
aeronave_motor_quantidade        0
aeronave_pmd                     0
aeronave_pmd_categoria           0
aeronave_assentos              454
aeronave_ano_fabricacao        303
aeronave_pais_fabricante         0
aeronave_pais_registro           0
aeronave_registro_categoria      0
aeronave_registro_segmento       0
aeronave_voo_origem              1
aeronave_voo_destino             1
aeronave_fase_operacao           0
aeronave_tipo_operacao           0
aeronave_nivel_dano              0
aeronave_fatalidades_total       0
dtype: int64

In [ ]:
ocorrencia_tipo.isna().sum() # contagem de NaN (nulos)

codigo_ocorrencia1           0
ocorrencia_tipo              0
ocorrencia_tipo_categoria    0
taxonomia_tipo_icao          0
dtype: int64